<a href="https://colab.research.google.com/github/random3770/exploratory-data-analysis/blob/main/experiment_3(21-7-26).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np

In [8]:
df1SE =  pd.DataFrame({ 'StudentID': [9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29],
                       'ScoreSE' : [22, 66, 31, 51, 71, 91, 56, 32, 52, 73, 92]})
df2SE =  pd.DataFrame({'StudentID': [2, 4, 6, 8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30],
                       'ScoreSE': [98, 93, 44, 77, 69, 56, 31, 53, 78, 93, 56, 77, 33, 56, 27]})

df1ML =  pd.DataFrame({ 'StudentID': [1, 3, 5, 7, 9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29],
                       'ScoreML' : [39, 49, 55, 77, 52, 86, 41, 77, 73, 51, 86, 82, 92, 23, 49]})
df2ML =  pd.DataFrame({'StudentID': [2, 4, 6, 8, 10, 12, 14, 16, 18, 20],
                       'ScoreML': [93, 44, 78, 97, 87, 89, 39, 43, 88, 78]})

In [9]:
dfSE = pd.concat([df1SE, df2SE], ignore_index=True)
dfML = pd.concat([df1ML, df2ML], ignore_index=True)

df = pd.concat([dfML, dfSE], axis=1)
display(df)

    StudentID  ScoreML  StudentID  ScoreSE
0         1.0     39.0          9       22
1         3.0     49.0         11       66
2         5.0     55.0         13       31
3         7.0     77.0         15       51
4         9.0     52.0         17       71
5        11.0     86.0         19       91
6        13.0     41.0         21       56
7        15.0     77.0         23       32
8        17.0     73.0         25       52
9        19.0     51.0         27       73
10       21.0     86.0         29       92
11       23.0     82.0          2       98
12       25.0     92.0          4       93
13       27.0     23.0          6       44
14       29.0     49.0          8       77
15        2.0     93.0         10       69
16        4.0     44.0         12       56
17        6.0     78.0         14       31
18        8.0     97.0         16       53
19       10.0     87.0         18       78
20       12.0     89.0         20       93
21       14.0     39.0         22       56
22       16.0     43.0         24       77
23       18.0     88.0         26       33
24       20.0     78.0         28       56
25        NaN      NaN         30       27

In [27]:
dfSE = pd.concat([df1SE, df2SE], ignore_index=True)
dfML = pd.concat([df1ML, df2ML], ignore_index=True)

df = dfSE.merge(dfML, how='inner')
display(df)

    StudentID  ScoreSE  ScoreML
0           9       22       52
1          11       66       86
2          13       31       41
3          15       51       77
4          17       71       73
5          19       91       51
6          21       56       86
7          23       32       82
8          25       52       92
9          27       73       23
10         29       92       49
11          2       98       93
12          4       93       44
13          6       44       78
14          8       77       97
15         10       69       87
16         12       56       89
17         14       31       39
18         16       53       43
19         18       78       88
20         20       93       78

In [11]:
dfSE = pd.concat([df1SE, df2SE], ignore_index=True)
dfML = pd.concat([df1ML, df2ML], ignore_index=True)

df = dfSE.merge(dfML, how='left')
display(df)

    StudentID  ScoreSE  ScoreML
0           9       22     52.0
1          11       66     86.0
2          13       31     41.0
3          15       51     77.0
4          17       71     73.0
5          19       91     51.0
6          21       56     86.0
7          23       32     82.0
8          25       52     92.0
9          27       73     23.0
10         29       92     49.0
11          2       98     93.0
12          4       93     44.0
13          6       44     78.0
14          8       77     97.0
15         10       69     87.0
16         12       56     89.0
17         14       31     39.0
18         16       53     43.0
19         18       78     88.0
20         20       93     78.0
21         22       56      NaN
22         24       77      NaN
23         26       33      NaN
24         28       56      NaN
25         30       27      NaN

In [12]:
dfSE = pd.concat([df1SE, df2SE], ignore_index=True)
dfML = pd.concat([df1ML, df2ML], ignore_index=True)

df = dfSE.merge(dfML, how='right')
display(df)

    StudentID  ScoreSE  ScoreML
0           1      NaN       39
1           3      NaN       49
2           5      NaN       55
3           7      NaN       77
4           9     22.0       52
5          11     66.0       86
6          13     31.0       41
7          15     51.0       77
8          17     71.0       73
9          19     91.0       51
10         21     56.0       86
11         23     32.0       82
12         25     52.0       92
13         27     73.0       23
14         29     92.0       49
15          2     98.0       93
16          4     93.0       44
17          6     44.0       78
18          8     77.0       97
19         10     69.0       87
20         12     56.0       89
21         14     31.0       39
22         16     53.0       43
23         18     78.0       88
24         20     93.0       78

In [28]:
dfSE_all = pd.concat([df1SE, df2SE], ignore_index=True).drop_duplicates(subset=['StudentID'])
dfML_all = pd.concat([df1ML, df2ML], ignore_index=True).drop_duplicates(subset=['StudentID'])

all_students_ids = pd.concat([dfSE_all['StudentID'], dfML_all['StudentID']]).unique()
total_students = len(all_students_ids)
print(f"Total unique students who appeared for exams: {total_students}")

Total unique students who appeared for exams: 30

In [29]:
se_only_students = dfSE_all[~dfSE_all['StudentID'].isin(dfML_all['StudentID'])]['StudentID'].nunique()
print(f"Students who only appeared for Software Engineering: {se_only_students}")

Students who only appeared for Software Engineering: 5

In [30]:
ml_only_students = dfML_all[~dfML_all['StudentID'].isin(dfSE_all['StudentID'])]['StudentID'].nunique()
print(f"Students who only appeared for Machine Learning: {ml_only_students}")

Students who only appeared for Machine Learning: 4

In [32]:
dfSE_all = pd.concat([df1SE, df2SE], ignore_index=True).drop_duplicates(subset=['StudentID'])
dfML_all = pd.concat([df1ML, df2ML], ignore_index=True).drop_duplicates(subset=['StudentID'])

all_students_ids = pd.concat([dfSE_all['StudentID'], dfML_all['StudentID']]).unique()
total_students = len(all_students_ids)
print(f"Total unique students who appeared for exams: {total_students}")

Total unique students who appeared for exams: 30

In [33]:
se_only_students = dfSE_all[~dfSE_all['StudentID'].isin(dfML_all['StudentID'])]['StudentID'].nunique()
print(f"Students who only appeared for Software Engineering: {se_only_students}")

Students who only appeared for Software Engineering: 5

In [34]:
ml_only_students = dfML_all[~dfML_all['StudentID'].isin(dfSE_all['StudentID'])]['StudentID'].nunique()
print(f"Students who only appeared for Machine Learning: {ml_only_students}")

Students who only appeared for Machine Learning: 4

In [35]:
data = {
    'OrderID': [1, 2, 3, 4, 5, 6, 7, 8, 9, 10],
    'Product': ['Laptop', 'Mouse', 'Keyboard', 'Monitor', 'Webcam', 'Speaker', 'Printer', 'Headphones', 'Tablet', 'Router'],
    'Company': ['ABC Inc.', 'XYZ Corp.', 'ABC Inc.', 'PQR Ltd.', 'XYZ Corp.', 'ABC Inc.', 'PQR Ltd.', 'XYZ Corp.', 'ABC Inc.', 'PQR Ltd.'],
    'UnitPrice': [1200.00, 25.00, 75.00, 300.00, 50.00, 150.00, 250.00, 70.00, 500.00, 80.00],
    'Quantity': [1, 2, 1, 1, 3, 2, 1, 1, 1, 2]
}
df = pd.DataFrame(data)
display(df.head(10))

   OrderID     Product    Company  UnitPrice  Quantity
0        1      Laptop   ABC Inc.     1200.0         1
1        2       Mouse  XYZ Corp.       25.0         2
2        3    Keyboard   ABC Inc.       75.0         1
3        4     Monitor   PQR Ltd.      300.0         1
4        5      Webcam  XYZ Corp.       50.0         3
5        6     Speaker   ABC Inc.      150.0         2
6        7     Printer   PQR Ltd.      250.0         1
7        8  Headphones  XYZ Corp.       70.0         1
8        9      Tablet   ABC Inc.      500.0         1
9       10      Router   PQR Ltd.       80.0         2

In [36]:
df['TotalPrice'] = df['UnitPrice'] * df['Quantity']
display(df.head(10))

   OrderID     Product    Company  UnitPrice  Quantity  TotalPrice
0        1      Laptop   ABC Inc.     1200.0         1      1200.0
1        2       Mouse  XYZ Corp.       25.0         2        50.0
2        3    Keyboard   ABC Inc.       75.0         1        75.0
3        4     Monitor   PQR Ltd.      300.0         1       300.0
4        5      Webcam  XYZ Corp.       50.0         3       150.0
5        6     Speaker   ABC Inc.      150.0         2       300.0
6        7     Printer   PQR Ltd.      250.0         1       250.0
7        8  Headphones  XYZ Corp.       70.0         1        70.0
8        9      Tablet   ABC Inc.      500.0         1       500.0
9       10      Router   PQR Ltd.       80.0         2       160.0

### Company Value Counts

In [37]:
df['Company'].value_counts()

Company
ABC Inc.     4
XYZ Corp.    3
PQR Ltd.     3
Name: count, dtype: int64

In [16]:
df.describe()

       StudentID    ScoreSE    ScoreML
count  25.000000  21.000000  25.000000
mean   13.400000  63.285714  66.720000
std     8.025999  23.229599  21.896575
min     1.000000  22.000000  23.000000
25%     7.000000  51.000000  49.000000
50%    13.000000  66.000000  77.000000
75%    19.000000  78.000000  86.000000
max    29.000000  98.000000  97.000000

In [17]:
data = np.arange(15).reshape((3,5))
indexers = ['Rainfall', 'Humidity', 'Wind']
dframe1 = pd.DataFrame(data, index=indexers, columns=['Bergen', 'Oslo', 'Trondheim', 'Stavanger', 'Kristiansand'])
display(dframe1)
stacked = dframe1.stack()
display(stacked)

          Bergen  Oslo  Trondheim  Stavanger  Kristiansand
Rainfall       0     1          2          3             4
Humidity       5     6          7          8             9
Wind          10    11         12         13            14

Rainfall  Bergen           0
          Oslo             1
          Trondheim        2
          Stavanger        3
          Kristiansand     4
Humidity  Bergen           5
          Oslo             6
          Trondheim        7
          Stavanger        8
          Kristiansand     9
Wind      Bergen          10
          Oslo            11
          Trondheim       12
          Stavanger       13
          Kristiansand    14
dtype: int64

In [18]:
display(stacked.unstack())

          Bergen  Oslo  Trondheim  Stavanger  Kristiansand
Rainfall       0     1          2          3             4
Humidity       5     6          7          8             9
Wind          10    11         12         13            14

In [19]:
series1 = pd.Series([000, 111, 222, 333], index=['zeros','ones', 'twos', 'threes'])
series2 = pd.Series([444, 555, 666], index=['fours', 'fives', 'sixs'])

frame2 = pd.concat([series1, series2], keys=['Number1', 'Number2'])
display(frame2.unstack())

         fives  fours   ones   sixs  threes   twos  zeros
Number1    NaN    NaN  111.0    NaN   333.0  222.0    0.0
Number2  555.0  444.0    NaN  666.0     NaN    NaN    NaN